/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class PuzzleCore {
  constructor(mode: number)
  moveSequence(sequence: string): boolean
  getPuzzle(): Array<Array<number>>
  duration(): string
  getCmdsStr(): string
  getMode(): number
}
